spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cookoff
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 21343